Config = Config or {}

-- For more info check: https://mt-scripts-documentations.gitbook.io/mt-script-documentation/

Config.foodAnimations = { -- Available animations on recipe creation menu
    -- Basic animations (Credits to rpemotes)
    cup = { label = 'Cup', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'prop_plastic_cup_02', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    burger = { label = 'Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'prop_cs_burger_01', pos = vec3(0.0, 0.0, -0.02), rot = vec3(0.0, 0.0, 30.00), bone = 60309 } },
    taco = { label = 'Taco', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'prop_taco_01', pos = vec3(-0.0170, 0.0070, -0.0210), rot = vec3(107.9846, -105.0251, 55.7779), bone = 60309 } },
    hotdog = { label = 'Hotdog', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'prop_cs_hotdog_02', pos = vec3(-0.030, 0.010, -0.010), rot = vec3(95.1071, 94.7001, -66.9179), bone = 60309 } },
    bagel = { label = 'Bagel', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'p_ing_bagel_01', pos = vec3(0.14, 0.05, 0.03), rot = vec3(145.3975, -53.8984, 4.8412), bone = 18905 } },
    donut = { label = 'Donut', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'prop_amb_donut', pos = vec3(0.13, 0.05, 0.02), rot = vec3(-50.0, 16.0, 60.0), bone = 18905 } },
    apple = { label = 'Apple', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'sf_prop_sf_apple_01b', pos = vec3(0.0, 0.0150, -0.0200), rot = vec3(-124.6964, -166.5760, 8.4572), bone = 60309 } },
    winebottle = { label = 'Wine Bottle', anim = { dict = 'amb@world_human_drinking@beer@female@idle_a', clip = 'idle_e' }, prop = { model = 'prop_wine_rose', pos = vec3(-0.0, 0.04, -0.19), rot = vec3(10.0, 0.0, 0.0), bone = 28422 } },
    coffee = { label = 'Coffee', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'p_amb_coffeecup_01', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    whiskey = { label = 'Whiskey', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'prop_drink_whisky', pos = vec3(0.01, -0.01, -0.06), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    whiskeybottle = { label = 'Whiskey Bottle', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'ba_prop_battle_whiskey_bottle_2_s', pos = vec3(0.0, 0.0, 0.5), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    beer = { label = 'Beer', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'prop_amb_beer_bottle', pos = vec3(0.0, 0.0, 0.06), rot = vec3(0.0, 15.0, 0.0), bone = 28422 } },
    wine = { label = 'Wine', anim = { dict = 'anim@heists@humane_labs@finale@keycards', clip = 'ped_a_enter_loop' }, prop = { model = 'prop_drink_redwine', pos = vec3(0.10, -0.03, 0.03), rot = vec3(-100.0, 0.0, -10.0), bone = 18905 } },
    flute = { label = 'Flute', anim = { dict = 'anim@heists@humane_labs@finale@keycards', clip = 'ped_a_enter_loop' }, prop = { model = 'prop_champ_flute', pos = vec3(0.10, -0.03, 0.03), rot = vec3(-100.0, 0.0, -10.0), bone = 18905 } },
    champagne = { label = 'Champagne', anim = { dict = 'anim@heists@humane_labs@finale@keycards', clip = 'ped_a_enter_loop' }, prop = { model = 'prop_drink_champ', pos = vec3(0.10, -0.03, 0.03), rot = vec3(-100.0, 0.0, -10.0), bone = 18905 } },
    beans = { label = 'Beans Bowl', anim = { dict = 'anim@scripted@island@special_peds@pavel@hs4_pavel_ig5_caviar_p1', clip = 'base_idle' }, prop = { model = 'h4_prop_h4_caviar_tin_01a', pos = vec3(0.0, 0.0300, 0.0100), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    dinner = { label = 'Dinner Dish', anim = { dict = 'anim@scripted@island@special_peds@pavel@hs4_pavel_ig5_caviar_p1', clip = 'base_idle' }, prop = { model = 'prop_cs_plate_01', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    sandwich = { label = 'Sandwich', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'prop_sandwich_01', pos = vec3(0.13, 0.05, 0.02), rot = vec3(-50.0, 16.0, 60.0), bone = 18905 } },

    -- G&N's Studios Burgershot food props - https://fivem.gnstud.io/package/5029847 (PAID! Delete if you don't have this pack!!)
    bleeder = { label = 'Bleeder Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_burger_bleeder_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    doubleshot = { label = 'Double Shot Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_burger_double_shot_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    fabulous = { label = 'Fabulous Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_burger_fabulous_6lb_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    glourious = { label = 'Glourious Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_burger_glorious_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    prickly = { label = 'Prickly Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_burger_prickly_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    simply = { label = 'Simply Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_burger_simply_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    bschickenwrap = { label = 'Burgershot Chicken Wrap', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_chicken_wrap_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 89.79), bone = 60309 } },
    bsfriesbox = { label = 'Burgershot Fries Box', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_fries_box_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 79.11), bone = 60309 } },
    bsgoatwrap = { label = 'Burgershot Goat Wrap', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_goat_wrap_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 89.79), bone = 60309 } },
    meteoriteic = { label = 'Meteorite Ice Cream', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_ice_cream_meteorite_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(179.48, 79.57, -131.28), bone = 60309 } },
    orangotanic = { label = 'Orang Otan Ice Cream', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_ice_cream_orang_otan_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(179.48, 79.57, -131.28), bone = 60309 } },
    bssoda = { label = 'Burgershot Soda', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'nels_soda_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    tacos = { label = 'Tacos', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'nels_tacos_prop', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 85.44), bone = 60309 } },

    -- G&N's Studios Up-N-Atom food prop - https://fivem.gnstud.io/package/5140403 (PAID! Delete if you don't have this pack!!)
    tcbburger = { label = 'The Triple Cheesy Bacon Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_upnatom_vw_the_triple_cheesy_bacon_burger', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    tripleburger = { label = 'The Triple Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_upnatom_vw_the_triple_burger', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    t10sbtcmvburger = { label = 'The 10 Slice of Bacon Triple Cheese Melt Version Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_upnatom_vw_the_10_slice_of_bacon_triple_cheese_melt_version', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    t10sbtcmburger = { label = 'The 10 Slice of Bacon Triple Cheese Melt Burger', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_upnatom_vw_the_10_slice_of_bacon_triple_cheese_melt', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    unasoda2 = { label = 'Up-N-Atom Soda 2', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'gn_upnatom_vw_soda_cup_1', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    unasoda = { label = 'Up-N-Atom Soda', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'gn_upnatom_vw_soda_cup', pos = vec3(0.0, 0.0, 0.05), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    unamilk = { label = 'Up-N-Atom Milk', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'gn_upnatom_vw_milk', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    unajumbos = { label = 'Up-N-Atom Jumbo Shake', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'gn_upnatom_vw_jumbo_shake', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    unafriesbox = { label = 'Up-N-Atom Fries Box', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_upnatom_vw_fries', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 60309 } },
    footlogcdog = { label = 'Footlong Chili Dog', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_upnatom_vw_footlong_chili_dog', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 89.55), bone = 60309 } },
    unacoffee = { label = 'Up-N-Atom Coffee', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'gn_upnatom_vw_coffee', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    
    -- G&N's Studios Clucking bell MLO food props - https://fivem.gnstud.io/package/5354683 (PAID! Delete if you don't have this pack!!)
    cbcup = { label = 'Clucking Bell Cup', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'gn_cluckin_cup', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    cbsoup = { label = 'Clucking Bell Soup', anim = { dict = 'amb@world_human_drinking@coffee@male@idle_a', clip = 'idle_c' }, prop = { model = 'gn_cluckin_soup', pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0), bone = 28422 } },
    cbfowl = { label = 'Clucking Bell Fowl', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_cluckin_fowl', pos = vec3(0.0, 0.0, 0.0), rot = vec3(-4.21, -48.68, -109.83), bone = 60309 } },
    cbfries = { label = 'Clucking Bell Fries', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_cluckin_fries', pos = vec3(0.0, 0.0, 0.0), rot = vec3(-9.29, -54.43, -103.59), bone = 60309 } },
    cbrings = { label = 'Clucking Bell Rings', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'gn_cluckin_rings', pos = vec3(0.0, 0.0, 0.0), rot = vec3(5.86, -50.96, -113.70), bone = 60309 } },

    -- BzZz Snack props - Download at https://discord.gg/hXtZMfy5k3
    bzzz_croissant = { label = 'Croissant', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'bzzz_new_snacks_croissant_a', pos = vec3(0.14, 0.04, 0.03), rot = vec3(-20.0, -30.0, 10.0), bone = 18905 } },
    bzzz_donut_a = { label = 'Donut A', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'bzzz_new_snacks_donut_a', pos = vec3(0.15, 0.06, 0.03), rot = vec3(30.0, 150.0, 10.0), bone = 18905 } },
    bzzz_donut_b = { label = 'Donut B', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'bzzz_new_snacks_donut_b', pos = vec3(0.15, 0.06, 0.03), rot = vec3(30.0, 150.0, 10.0), bone = 18905 } },
    bzzz_peanuts = { label = 'Peanuts', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'bzzz_new_snacks_peanuts_a', pos = vec3(0.15, 0.07, 0.0), rot = vec3(30.0, 150.0, 10.0), bone = 18905 } },
    bzzz_pretzels = { label = 'Pretzels', anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' }, prop = { model = 'bzzz_new_snacks_pretzels_a', pos = vec3(0.16, 0.04, 0.03), rot = vec3(-70.0, 140.0, 10.0), bone = 18905 } },
    bzzz_pepsiloca_a = { label = 'Pepsiloca A', anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' }, prop = { model = 'bzzz_new_snacks_pepsiloca_a', pos = vec3(0.12, 0.03, 0.03), rot = vec3(-60.0, 100.0, -20.0), bone = 18905 } },
    bzzz_pepsiloca_b = { label = 'Pepsiloca B', anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' }, prop = { model = 'bzzz_new_snacks_pepsiloca_b', pos = vec3(0.12, 0.03, 0.03), rot = vec3(-60.0, 100.0, -20.0), bone = 18905 } },
    bzzz_energy = { label = 'Energy', anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' }, prop = { model = 'bzzz_new_snacks_energy_a', pos = vec3(0.12, 0.0, 0.05), rot = vec3(-60.0, 100.0, -20.0), bone = 18905 } },
}